/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <string.h>
/* Header for class com_example_prjtest00_MainActivity */

#ifndef _Included_com_example_prjtest00_MainActivity
#define _Included_com_example_prjtest00_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_prjtest00_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_prjtest00_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
