/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <android/log.h>

/* Header for class com_example_swigprj_Transmission */

#ifndef _Included_com_example_swigprj_Transmission
#define _Included_com_example_swigprj_Transmission
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_swigprj_Transmission
 * Method:    transferString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_swigprj_Transmission_transferString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_swigprj_Transmission
 * Method:    transferPerson
 * Signature: (Lcom/example/swigprj/Person;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_example_swigprj_Transmission_transferPerson
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
