/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duicky_LogUtils */

#ifndef _Included_com_duicky_LogUtils
#define _Included_com_duicky_LogUtils
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
