/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.southgnss.coordtransform;

public class ProjectPara {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ProjectPara(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProjectPara obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        testSwigJNI.delete_ProjectPara(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUnused(int value) {
    testSwigJNI.ProjectPara_unused_set(swigCPtr, this, value);
  }

  public int getUnused() {
    return testSwigJNI.ProjectPara_unused_get(swigCPtr, this);
  }

  public ProjectPara() {
    this(testSwigJNI.new_ProjectPara(), true);
  }

}
