/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.southgnss.coordtransform;

public class testSwigJNI {
	static {
		System.loadLibrary("testSwig");
	}
  public final static native void ProjectPara_unused_set(long jarg1, ProjectPara jarg1_, int jarg2);
  public final static native int ProjectPara_unused_get(long jarg1, ProjectPara jarg1_);
  public final static native long new_ProjectPara();
  public final static native void delete_ProjectPara(long jarg1);
  public final static native void Add(double[] jarg1, double[] jarg2);
  public final static native void GetName(byte[] jarg1, int jarg2);
}
