/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.southgnss.coordtransform;

public class testSwig {
  public static void Add(double[] arg0, double[] arg1) {
    testSwigJNI.Add(arg0, arg1);
  }

  public static void GetName(byte[] BYTE, int nsize) {
    testSwigJNI.GetName(BYTE, nsize);
  }

}
